### ISSUE TITLE
binlog time issue

### ISSUE THREAD

**Issue by kuibing126** [morganstanley/binlog#102]
[1973-10-08 22:26:17.037033700] [5444] [INFO] [G:\SVN_work\ETFCPP\trunk3\common\BinLogConsume.cpp:16 Svc] Task thread started

Hi,   I use TSC binlog to logging. why the now date is **1973-10-08**?

I use the following command to convert:
**bread -f "[%d] [%n] [%S] [%F:%L %M] %m" QuoteSvrXX.blog > QuoteSvr.txt**

I defined a series of TSC macros:
`

#define TSC_INFO_W(writer, ...) BINLOG_CREATE_SOURCE_AND_EVENT_IF(writer, binlog::Severity::info, main, __rdtsc(), __VA_ARGS__)
#define TSC_TRACE_W(writer, ...) BINLOG_CREATE_SOURCE_AND_EVENT_IF(writer, binlog::Severity::trace, main, __rdtsc(), __VA_ARGS__)
#define TSC_DEBUG_W(writer, ...) BINLOG_CREATE_SOURCE_AND_EVENT_IF(writer, binlog::Severity::debug, main, __rdtsc(), __VA_ARGS__)
#define TSC_ERROR_W(writer, ...) BINLOG_CREATE_SOURCE_AND_EVENT_IF(writer, binlog::Severity::error, main, __rdtsc(), __VA_ARGS__)
#define TSC_CRITICAL_W(writer, ...) BINLOG_CREATE_SOURCE_AND_EVENT_IF(writer, binlog::Severity::critical, main, __rdtsc(), __VA_ARGS__)
#define TSC_WARN_W(writer, ...) BINLOG_CREATE_SOURCE_AND_EVENT_IF(writer, binlog::Severity::warning, main, __rdtsc(), __VA_ARGS__)
	`

Attached is my binlog wrapper.

Thank you

**Comment by kuibing126** [comment]
[Uploading LogManager.zip…]()

**Comment by kuibing126** [comment]
[LogManager.zip](https://github.com/morganstanley/binlog/files/5877985/LogManager.zip)

**Comment by kuibing126** [comment]
[QuoteSvr20210127103243.zip](https://github.com/morganstanley/binlog/files/5878372/QuoteSvr20210127103243.zip)

Here's my generated blog file.

**Comment by kuibing126** [comment]
![image](https://user-images.githubusercontent.com/75358276/105959739-4520ef00-60b7-11eb-8940-550fe9569813.png)

one more question, sometimes, when I converting blog to text by bread, I will get this error:
**Exception:Range overflow 808464683 > 19**

How do I handle this error?

Attached is blog example.Thank you
[d.zip](https://github.com/morganstanley/binlog/files/5878510/d.zip)

**Comment by erenon** [comment]
Hi, it's not feasible to me to fiddle with attached zips. Please upload a minimal, working example, that reproduces either of your issues. Strip it down to the bare essentials, leaving only a minimal core - no wrapper types etc needed. Thanks.

**Comment by kuibing126** [comment]
I found the root causes. 

If I encapsulate binlog as a DLL, intput to my project, then the logging date is **1973-08-25**
If put .cpp and .h to my exe project directly, then logging date  is OK.

but why there's wrong date when I use binlog as DLL?

**Comment by kuibing126** [comment]
> Hi, it's not feasible to me to fiddle with attached zips. Please upload a minimal, working example, that reproduces either of your issues. Strip it down to the bare essentials, leaving only a minimal core - no wrapper types etc needed, and upload it as a GitHub gist. Thanks.

Hey, I get it solved by my self.

Only "**Exception:Range overflow 808464683 > 19**" issues not resolved when converting by bread. can you help me for this issue?

Thank you

**Comment by erenon** [comment]
Sure thing.  Please upload a minimal, working example, that reproduces either of your issues. Strip it down to the bare essentials, leaving only a minimal core - no wrapper types etc needed, and upload it as a GitHub gist. Thanks.

**Comment by kuibing126** [comment]
> Sure thing. Please upload a minimal, working example, that reproduces either of your issues. Strip it down to the bare essentials, leaving only a minimal core - no wrapper types etc needed, and upload it as a GitHub gist. Thanks.
![image](https://user-images.githubusercontent.com/75358276/106221467-a3191800-6218-11eb-8239-317f73363b49.png)

Hi, When I try to tail -f blog files, I got this error.  How can I correctly use tail for blog?
**[bread] Exception: vector too long**

[QuoteSvr20210129092743.zip](https://github.com/morganstanley/binlog/files/5891100/QuoteSvr20210129092743.zip)

**Comment by kuibing126** [comment]
[blogdemo.zip](https://github.com/morganstanley/binlog/files/5901769/blogdemo.zip)
![image](https://user-images.githubusercontent.com/75358276/106413059-18d4ec00-6484-11eb-9f89-509fcfa11470.png)


Hi, when I **use tail -f 11.blog | bread** command, the tail progress will be blocked as attacched blog file.

do you know how to handle this issue?

**Comment by erenon** [comment]
Use tail as documented:

```
tail -c0 -F logfile.blog | bread
```

http://binlog.org/UserGuide.html#bread

Without -c0  tail will skip important parts of the logfile

**Comment by kuibing126** [comment]
> Use tail as documented:
> 
> ```
> tail -c0 -F logfile.blog | bread
> ```
> 
> http://binlog.org/UserGuide.html#bread
> 
> Without -c0 tail will skip important parts of the logfile

![image](https://user-images.githubusercontent.com/75358276/106423152-d1a62580-649a-11eb-8d6c-7296565fa786.png)


use **tail -c0 -F**,  I got:

TAIL:can't open -F
[bread]Exception: vector too long

**Comment by erenon** [comment]
It seems the  `tail` version you are using does not support this flag combination or the way those flags are specified. This is unrelated to binlog, unfortunately I have no windows tail experience.
