### ISSUE TITLE
Support serialization of std..time_point

### ISSUE THREAD

**Issue by andrewkcorcoran** [morganstanley/binlog#103]
It would be nice if serilization of `std::chrono::time_point<std::chrono::system_clock, TDuration>` was natively supported. The nanoseconds since epoch could be serialized to binary and then bread could deserilize in the same time format as used for the log timestamps (and also match the user timestamp format override if specified).

C++20 specifies that the epoch for `std::system_clock` must be the Unix epoch and while that wasn't mandated for C++ versions previously it was a defacto standard on nearly every platform.

**Comment by erenon** [comment]
Thanks for reporting. It is covered by: https://github.com/morganstanley/binlog/issues/61
#61 is not implemented, because I simply couldn't design a nice solution yet. Sorry about that.

**Comment by erenon** [comment]
See https://github.com/morganstanley/binlog/pull/108
