### ISSUE TITLE
Release Process

### ISSUE THREAD

**Issue by andrewkcorcoran** [morganstanley/binlog#118]
Hi,

What's the release idiom for binlog? Is it following a "live at head" philosophy or are versioned releases the only code considered stable and production ready?

The reason I ask is that I'd like to start using some of the new features that have been added in the year since the last release. Without documentation in the README.md or similar saying that the repo is following a "live at head" philosophy and master is considered production quality it's not trivial to get approvals to use the new features.

**Comment by erenon** [comment]
> Without documentation in the README.md or similar saying that the repo is following a "live at head" philosophy and master is considered production quality it's not trivial to get approvals to use the new features.

That's why we have releases - to make ppl comfortable who want to use releases : )
Otherwise, every commit goes through the same pipeline, and a released commit is no better than an unreleased one. I'll add a note to the README (live at head), and will prepare a release if time permits.
