### ISSUE TITLE
tsc time issue

### ISSUE THREAD

**Issue by kuibing126** [morganstanley/binlog#121]
![image](https://user-images.githubusercontent.com/75358276/116663992-6ea92980-a9ca-11eb-900f-f6a3f6af506c.png)

Hi ,I read tsc value as above. But my log time was not correct.

![image](https://user-images.githubusercontent.com/75358276/116664332-e414fa00-a9ca-11eb-88a8-9b992957c926.png)

[2021-04-30 **15:21:15.**031082254] [139967332558592] [INFO] [HXQuoteDemo/HXQuoteDemo.cpp:295 OnRtnMarketData] **15:22:35.**000036,code:510050

actual time is 15:22:35, but binlog time is 15:21:15.

can you help me?

**Comment by kuibing126** [comment]
![image](https://user-images.githubusercontent.com/75358276/116666704-db71f300-a9cd-11eb-8021-92da81204290.png)

![image](https://user-images.githubusercontent.com/75358276/116666776-f5133a80-a9cd-11eb-87c6-23ab2dfc55a5.png)

attached is frequency value on my machine.

**Comment by erenon** [comment]
The last image doesn't show how the "actual time" is computed. However, there's no way I could figure out what's going on by looking at partial images of your source code. TSC timetsamping is a difficult topic, subject to a large number of issues (e.g: see comment in the code that you copied from google benchmark, or think about clock skew, that requires sending TscSync entries peridocally, etc).

**Comment by kuibing126** [comment]
Can you provide a clock skew example?
thank you



---Original---
From: "Thaler ***@***.***&gt;
Date: Fri, Apr 30, 2021 19:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [morganstanley/binlog] tsc time issue (#121)




 
The last image doesn't show how the "actual time" is computed. However, there's no way I could figure out what's going on by looking at partial images of your source code. TSC timetsamping is a difficult topic, subject to a large number of issues (e.g: see comment in the code that you copied from google benchmark, or think about clock skew, that requires sending TscSync entries peridocally, etc).

**Comment by kuibing126** [comment]
> The last image doesn't show how the "actual time" is computed. However, there's no way I could figure out what's going on by looking at partial images of your source code. TSC timetsamping is a difficult topic, subject to a large number of issues (e.g: see comment in the code that you copied from google benchmark, or think about clock skew, that requires sending TscSync entries peridocally, etc).

![image](https://user-images.githubusercontent.com/75358276/117225183-501cb580-ae44-11eb-9f6b-80f5943d3a78.png)

![image](https://user-images.githubusercontent.com/75358276/117225156-41360300-ae44-11eb-98b4-9c422e8f4f0d.png)

Attach my local time function GetCurTimeStr()

**Comment by kuibing126** [comment]
![image](https://user-images.githubusercontent.com/75358276/117254895-96d9d200-ae7b-11eb-962d-aa99d5e249ae.png)

In win32 platform, the time stamp of binlog seems the same with GetCurTimeStr().

**Comment by erenon** [comment]
Clock skew is described here: https://en.wikipedia.org/wiki/Clock_skew
If you experience that the tsc timestamp increasingly drifts away from the NTP synchronized clock, you can try adding a ClockSync entry periodically (e.g: once in a minute), or improve the way the tsc frequency is calculated.
