### ISSUE TITLE
binlog timestamp in different thread

### ISSUE THREAD

**Issue by kuibing126** [morganstanley/binlog#122]
![image](https://user-images.githubusercontent.com/75358276/117791178-9f1b7e00-b27c-11eb-8aec-91d5f1923bdc.png)

Hi,

Attached is my log of using binlog to print in different thread. 
As above image, thread [2368]'s timestamp occurs before thread[5060].

Actually, I hope to get the following sorts:

[2021-05-10 10:01:32.**236551613**] [5060][INFO]
[2021-05-10 10:01:32.**246469529**] [2368] [INFO]

**Comment by erenon** [comment]
`bread` does not sort the events by default (to be faster). `bread -s` does sort them. See: http://binlog.org/UserGuide.html#bread

**Comment by kuibing126** [comment]
bread -f "[%%d] [%%n] [%%S] [%%F:%%L %%M] %%m" -s quote.blog


I use above command, but seems bread were blocked. no any result?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "morganstanley/binlog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 晚上8:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [morganstanley/binlog] binlog timestamp in different thread (#122)





 
bread does not sort the events by default (to be faster). bread -s does sort them. See: http://binlog.org/UserGuide.html#bread
