### ISSUE TITLE
bread -s were blocked

### ISSUE THREAD

**Issue by kuibing126** [morganstanley/binlog#123]
[binlogMno.zip](https://github.com/morganstanley/binlog/files/6463081/binlogMno.zip)

Hi,

Attached my example.

When I use
 bread -f "[%d] [%n] [%S] [%F:%L %M] %m" **-s** QuoteSvr20210510090801.blog

bread will be blocked.

If I remove '-s', there's no problem. How can I correctly use '-s' option?

**Comment by erenon** [comment]
Unable to reproduce.
