### ISSUE TITLE
[BUG] Compile failed for packed attribute struct

### ISSUE THREAD

**Issue by MashoujiangPlusAI** [morganstanley/binlog#144]
Hi everyone,

I don't want to be a nuisance :), but I meet another compiling issue for below code, which is a struct with packed attribute. And without the attribute, we could compile the code successfully. See below code or [here demo](https://codebeautify.org/alleditor/y22dab776)

> #include <binlog/binlog.hpp>
> 
> typedef struct
> {
>   uint32_t msg_id;
> }\_\_attribute\_\_((packed)) Message;
> 
> int main()
> {
>   Message* message = new Message;
>   BINLOG_INFO("Hello {}!", message->msg_id);
>   return 0;
> }
> 
![image](https://user-images.githubusercontent.com/89773466/170665818-a8190ea4-40b0-4cae-ae1c-ec8efcd08048.png)

**Comment by erenon** [comment]
This happens because GCC doesn't allow to form a reference to a packed field. Workaround for a single field:

```
  BINLOG_INFO("Hello {}!", std::uint32_t{message->msg_id});
```

To make the whole struct loggable with `BINLOG_ADAPT_STRUCT`, introduce getters, that simply return the field by value: http://binlog.org/UserGuide.html#logging-user-defined-structures

**Comment by MashoujiangPlusAI** [comment]
Got it, thank you very much!
