### ISSUE TITLE
With piping, a live logfile that is being written by the application can be read... not output

### ISSUE THREAD

**Issue by stockxiay** [morganstanley/binlog#166]
Hi,body
 I use tail -c0 -F logfile.blog | bread then output nothing

**Comment by erenon** [comment]
Hi, how do you write the logfile?

**Comment by stockxiay** [comment]
run bread is work,when run tail -c0 -F logfile.blog | bread then nothing output

**Comment by erenon** [comment]
Thanks for the report, the documentation was incorrect, it is being fixed by #167. The correct usage is:

```tail -c +0 -F logfile.blog | bread```
