### ISSUE TITLE
Compilation fails using MinGW

### ISSUE THREAD

**Issue by egelja** [morganstanley/binlog#169]
The following lines should be changed from `$<CXX_COMPILER_ID:MSVC>` to `$<PLATFORM_ID:Windows>` to compile properly on windows with MinGW.

https://github.com/morganstanley/binlog/blob/a6ef529c363d0be91f8c76721111d4ef6ce48758/CMakeLists.txt#L201
https://github.com/morganstanley/binlog/blob/a6ef529c363d0be91f8c76721111d4ef6ce48758/CMakeLists.txt#L218
https://github.com/morganstanley/binlog/blob/a6ef529c363d0be91f8c76721111d4ef6ce48758/CMakeLists.txt#L336

**Comment by erenon** [comment]
Thanks for reporting! I tried to add MinGW support in #170, but the tests fail to start (Exit code 0xc0000139), due to some missing DLLs, apparently - something is wrong with the environment. I don't have a windows install, can you check what's wrong with the github action?
