### ISSUE TITLE
Precision on floating point members in struct

### ISSUE THREAD

**Issue by lawrence-koh** [morganstanley/binlog#175]
Hi, I have a struct that has a `long double` member.

After using `BINLOG_ADAPT_STRUCT` and logging the struct member, when the output file is read using `bread`, there is some loss of precision.

e.g. `1234234.0234242` becomes `1.23423e+06`.

Is there a way to control the precision that is being printed by `bread`?

**Comment by erenon** [comment]
Thanks for the report, the situation is being improved in: https://github.com/morganstanley/binlog/pull/176/files

**Comment by lawrence-koh** [comment]
@erenon thank you for your help on this!
