### ISSUE TITLE
Native support for logging pointer addresses

### ISSUE THREAD

**Issue by andrewkcorcoran** [morganstanley/binlog#41]
Currently attempting to pass a `void *` pointer as an argument results in a compile error requiring the user to do a `reinterpret_cast` to `std::uintptr_t` or similar. It would be great if this cast could be moved into the logging framework so that the user isn't required to do it. Even better, binlog could treat pointers as first class citizens by having a new mserialize tag so that `bread` would log them by default in 0x format, similar to printf.

**Comment by erenon** [comment]
This touches the broad, and unresolved topic of pretty printing. Adding a new tag could be done, but that's a format breaking change, and not a complete solution. For example, consider physical units: we'd like to read `10 m/s`, and not `ratio<meters, seconds>{ num: 20, den: 2 }`, or currency: `$10` or `Dollars{ value: 10 }`. Similarly, a pointer address can be printed as `0x7f123`, and represented as `Pointer{ void* value; };`.

To be able to do that, I'm considering a pretty printer mini-language, embedded into the log as optional special entries (therefore [backward compatible](https://github.com/Morgan-Stanley/binlog/commit/46cb9f2e37d2157b7aef95dcaf3cd8d832846c82)), but such a language would be complicated, and sounds wasteful to invent.

**Comment by andrewkcorcoran** [comment]
I think sticking to supporting C++ fundamental types is completely acceptable, and a more complex type needs to be decomposed into multiple fundamental ones. Though I would argue that pointers could be classed as fundamental types and therefore should be supported out of the box.

Regarding pretty printing. Perhaps a half way solution is to allow format strings within then `{}` similar to https://en.cppreference.com/w/cpp/utility/format/formatter#Standard_format_specification. This would specify the default formatting output of bread (but still allow the existing customisation).

**Comment by erenon** [comment]
That format language could help when logging raw addresses directly, but fails for other cases, e.g: logging a container of pointers, or logging a struct that contains a pointer as a field.
A different motivating example for pretty printing: `std::chrono::system_clock::time_point`. It can be logged as a single `u64`, but displaying it as such, is not useful.
